// Generated by npm run images:responsive. Do not edit manually.

export interface ResponsiveImageVariant {
    src: string;
    width: number;
}

export interface ResponsiveImageMetadata {
    width: number;
    height: number;
    variants: readonly ResponsiveImageVariant[];
}

export const responsiveImages: Record<string, ResponsiveImageMetadata> = {
    "/photography/1.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/1-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/1-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/1-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/2.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/2-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/2-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/2-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/3.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/3-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/3-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/3-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/4.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/4-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/4-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/4-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/5.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/5-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/5-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/5-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/6.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/6-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/6-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/6-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/7.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/7-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/7-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/7-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/8.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/8-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/8-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/8-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/9.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/9-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/9-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/9-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/10.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/10-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/10-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/10-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/11.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/11-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/11-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/11-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/12.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/12-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/12-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/12-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/13.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/13-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/13-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/13-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/14.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/14-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/14-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/14-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/15.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/15-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/15-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/15-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/16.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/16-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/16-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/16-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/17.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/17-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/17-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/17-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/18.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/18-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/18-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/18-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/19.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/19-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/19-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/19-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/20.webp": {
        "width": 5764,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/20-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/20-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/20-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/21.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/21-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/21-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/21-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/22.webp": {
        "width": 4000,
        "height": 6000,
        "variants": [
            {
                "src": "/responsive/photography/22-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/22-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/22-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/23.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/23-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/23-640.webp",
                "width": 640
            }
        ]
    },
    "/photography/24.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/24-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/24-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/24-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/25.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/25-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/25-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/25-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/26.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/26-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/26-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/26-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/27.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/27-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/27-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/27-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/28.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/28-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/28-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/28-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/29.webp": {
        "width": 4000,
        "height": 6000,
        "variants": [
            {
                "src": "/responsive/photography/29-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/29-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/29-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/30.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/30-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/30-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/30-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/31.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/31-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/31-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/31-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/32.webp": {
        "width": 4488,
        "height": 2367,
        "variants": [
            {
                "src": "/responsive/photography/32-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/32-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/32-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/33.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/33-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/33-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/33-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/34.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/34-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/34-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/34-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/35.webp": {
        "width": 4277,
        "height": 3487,
        "variants": [
            {
                "src": "/responsive/photography/35-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/35-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/35-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/36.webp": {
        "width": 4608,
        "height": 3456,
        "variants": [
            {
                "src": "/responsive/photography/36-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/36-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/36-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/37.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/37-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/37-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/37-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/38.webp": {
        "width": 6000,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/38-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/38-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/38-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/39.webp": {
        "width": 4000,
        "height": 2666,
        "variants": [
            {
                "src": "/responsive/photography/39-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/39-640.webp",
                "width": 640
            }
        ]
    },
    "/photography/40.webp": {
        "width": 4000,
        "height": 2666,
        "variants": [
            {
                "src": "/responsive/photography/40-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/40-640.webp",
                "width": 640
            }
        ]
    },
    "/photography/41.webp": {
        "width": 4000,
        "height": 2666,
        "variants": [
            {
                "src": "/responsive/photography/41-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/41-640.webp",
                "width": 640
            }
        ]
    },
    "/photography/42.webp": {
        "width": 4000,
        "height": 2366,
        "variants": [
            {
                "src": "/responsive/photography/42-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/42-640.webp",
                "width": 640
            }
        ]
    },
    "/photography/43.webp": {
        "width": 4000,
        "height": 2666,
        "variants": [
            {
                "src": "/responsive/photography/43-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/43-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/photography/43-1280.webp",
                "width": 1280
            }
        ]
    },
    "/photography/44.webp": {
        "width": 2666,
        "height": 4000,
        "variants": [
            {
                "src": "/responsive/photography/44-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/44-640.webp",
                "width": 640
            }
        ]
    },
    "/photography/45.webp": {
        "width": 4000,
        "height": 2666,
        "variants": [
            {
                "src": "/responsive/photography/45-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/45-640.webp",
                "width": 640
            }
        ]
    },
    "/photography/46.webp": {
        "width": 4000,
        "height": 2666,
        "variants": [
            {
                "src": "/responsive/photography/46-320.webp",
                "width": 320
            },
            {
                "src": "/responsive/photography/46-640.webp",
                "width": 640
            }
        ]
    },
    "/arts/1.webp": {
        "width": 3401,
        "height": 3401,
        "variants": [
            {
                "src": "/responsive/arts/1-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/arts/1-960.webp",
                "width": 960
            },
            {
                "src": "/responsive/arts/1-1920.webp",
                "width": 1920
            }
        ]
    },
    "/arts/2.webp": {
        "width": 4553,
        "height": 4553,
        "variants": [
            {
                "src": "/responsive/arts/2-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/arts/2-960.webp",
                "width": 960
            },
            {
                "src": "/responsive/arts/2-1920.webp",
                "width": 1920
            }
        ]
    },
    "/arts/3.webp": {
        "width": 2275,
        "height": 2275,
        "variants": [
            {
                "src": "/responsive/arts/3-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/arts/3-960.webp",
                "width": 960
            },
            {
                "src": "/responsive/arts/3-1920.webp",
                "width": 1920
            }
        ]
    },
    "/arts/4.webp": {
        "width": 536,
        "height": 536,
        "variants": []
    },
    "/arts/5.webp": {
        "width": 524,
        "height": 524,
        "variants": []
    },
    "/arts/6.webp": {
        "width": 438,
        "height": 438,
        "variants": []
    },
    "/arts/7.webp": {
        "width": 472,
        "height": 472,
        "variants": []
    },
    "/arts/8.webp": {
        "width": 2310,
        "height": 3500,
        "variants": [
            {
                "src": "/responsive/arts/8-640.webp",
                "width": 640
            }
        ]
    },
    "/arts/9.webp": {
        "width": 3464,
        "height": 2450,
        "variants": [
            {
                "src": "/responsive/arts/9-640.webp",
                "width": 640
            },
            {
                "src": "/responsive/arts/9-960.webp",
                "width": 960
            }
        ]
    }
};
